# Generated by Django 3.2.5 on 2021-07-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_content_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='createdAt',
        ),
    ]
