# Generated by Django 3.2.5 on 2021-07-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_content_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='owner',
        ),
    ]
